### ISSUE TITLE
qb-target 

### ISSUE THREAD

**Issue by cummins24v2** [trclassic92/qb-simplefarming#1]
for some reason i can only use the target on the cows and the apple trees and nothing else seems to work

**Comment by trclassic92** [comment]
Are you getting any console or any F8 errors?

**Comment by trclassic92** [comment]
> for some reason i can only use the target on the cows and the apple trees and nothing else seems to work

Another option you can do is try updating your qb-target system

https://github.com/BerkieBb/qb-target

https://github.com/loljoshie/qb-target
