### ISSUE TITLE
Moving seller not working

### ISSUE THREAD

**Issue by Nick5M420** [trclassic92/qb-simplefarming#13]
ive tried multiple times to move the seller, and the target only works in the original spot, any idea what im doing wrong? is it just the config im supposto change or something else

**Comment by trclassic92** [comment]
Config.coords

**Comment by Nick5M420** [comment]
yeah ive tried that the npc moves but nomatter what i do i cant get target to show up unless its in the original spot

**Comment by trclassic92** [comment]
> yeah ive tried that the npc moves but nomatter what i do i cant get target to show up unless its in the original spot

This is not a issue,, all you have to do is change the coords and also the target coord and it will move the peds location
