### ISSUE TITLE
Hello , no issue , just a question

### ISSUE THREAD

**Issue by Maureks** [trclassic92/qb-simplefarming#14]
Love the script !

Is it possible to make it so , that only players with the farmer job can see the blips ? 
What do I need to do if so?

Thanks in advance!

**Comment by Nick5M420** [comment]
+1 if you could add this to a specific job it would be great!

**Comment by trclassic92** [comment]
You can do all that your self by adding a job check to the target

**Comment by Maureks** [comment]
> You can do all that your self by adding a job check to the target

I've allready done that, I'am talking about the blips on the Map , so they only be showed for the players with the job

**Comment by trclassic92** [comment]
Sure just go look at how other jobs have their blips and add it 👍

**Comment by Maureks** [comment]
Do I have to delete anything from the script? Or just the added stuff would be sufficient?

**Comment by Maureks** [comment]
Can you give an example of a default script wich has a good example of it?
