### ISSUE TITLE
Issue with newest qb-target

### ISSUE THREAD

**Issue by tokidi** [trclassic92/qb-simplefarming#15]
Cant press anything with target, others scripts working, but this not working, not showing options  https://prnt.sc/0j_pg6Q4hOTW

**Comment by trclassic92** [comment]
> Cant press anything with target, others scripts working, but this not working, not showing options https://prnt.sc/0j_pg6Q4hOTW

You have a out of date target

**Comment by HATE-dev** [comment]
targets are not working

**Comment by trclassic92** [comment]
Target does work you just have to update it to the lastest version of qb-target. 

Target has nothing to do with the farming script if it's not working then it's a qb-target issue.
