### ISSUE TITLE
Processing Raw Sausage checks for wrong item

### ISSUE THREAD

**Issue by instigate77** [trclassic92/qb-simplefarming#17]
This should be checking for:  qb-simplefarming:rawsausage

RegisterNetEvent('qb-simplefarming:sausageprocessing', function()
  QBCore.Functions.TriggerCallback('qb-simplefarming:rawsausage', function(rawbeef)

But it's checking qb-simplefarming:rawpork'
  QBCore.Functions.TriggerCallback('qb-simplefarming:rawpork', function(rawbeef)

**Comment by instigate77** [comment]
https://github.com/trclassic92/qb-simplefarming/blob/66c806e0bd090cf3cc75d2b3cbd56ebd9f250a67/client/main.lua#L1467

**Comment by trclassic92** [comment]
It doesn't matter which the function name is it's just calling if you have it or not. I can call it pineapples if I wanted to
