### ISSUE TITLE
Cow milk and Pig meat not working 

### ISSUE THREAD

**Issue by nutter887** [trclassic92/qb-simplefarming#18]
Cow milk and Pic meat not working  but farming working.

**Comment by trclassic92** [comment]
> Cow milk and Pic meat not working but farming working.

What do you mean

**Comment by fluky5757** [comment]
everything is good the cow milk every time i have to restart qb-target and your script to work 
all problem box zon when i use target

**Comment by nutter887** [comment]
I found it! problem is about my hunthing job because it's used same cow with qb target. Your script it's work!
