### ISSUE TITLE
issue & question

### ISSUE THREAD

**Issue by shadowTW** [trclassic92/qb-simplefarming#19]
why sometimes the qb-target doesn't work on this script, like on other scripts it works

**Comment by trclassic92** [comment]
Can you explain what isn’t working for the target?

**Comment by trclassic92** [comment]
Well which peds?

**Comment by trclassic92** [comment]
I don’t even see you trying to target the peds on those screenshots.

**Comment by trclassic92** [comment]
What target version do you use.

**Comment by fluky5757** [comment]
i have same issue in cow only

**Comment by trclassic92** [comment]
Well the lastest qb-target is working for me when I just tried it.
