### ISSUE TITLE
first issue

### ISSUE THREAD

**Issue by madalex24** [trclassic92/qb-simplefarming#2]
![qb farming error1](https://user-images.githubusercontent.com/91700454/155841960-0c3cd93e-5849-4850-ad48-7a8a8e9ca853.png)

Just saw this in the f8 menu when loaded up fivem.

is this a easy fix?

**Comment by trclassic92** [comment]
Do you have qb-target and polyzone?

**Comment by madalex24** [comment]
yes

**Comment by trclassic92** [comment]
> yes

What qb-target version do you use?

**Comment by trclassic92** [comment]
> yes

Try downloading the lastest update that I just pushed to the repo and let me know if that works for you.

**Comment by madalex24** [comment]
It seems to work now thank you.
I went to pick apples and it says item doesn't exist.
