### ISSUE TITLE
Cow Milking

### ISSUE THREAD

**Issue by itzreekcan** [trclassic92/qb-simplefarming#23]
When I go to milk cows it is only showing the option to slaughter the cow and not to milk. The script previously worked but now it is not giving me the option.

**Comment by trclassic92** [comment]
> When I go to milk cows it is only showing the option to slaughter the cow and not to milk. The script previously worked but now it is not giving me the option.

If you have any issues related to this resource I am able to help you out more at my discord server https://discord.gg/zRCdhENsHG and there I also have A FAQ channel that has questions about issues just as this one that have been answered in the paste
