### ISSUE TITLE
Issues with sausages

### ISSUE THREAD

**Issue by skellykat** [trclassic92/qb-simplefarming#25]
https://i.imgur.com/Xtcmb13.png
https://i.imgur.com/2ty77wr.png
https://i.imgur.com/js6wnaw.png
Hi found an issue for some reason after I have cooked so many sausages apparently I don't have any more sausages to cook even though I have sausage in my inventory i have tried restarting the resource but for some reason, it still fails. Also, I found an error in your code you put sausage_processing instead of sausage_progressbar. Hope you can find a fix for this. PS the cooked sausages in my inventory are 6, not 0 my screenshot is broken. Thank you for such an amazing resource keep up the amazing work.

**Comment by trclassic92** [comment]
> https://i.imgur.com/Xtcmb13.png https://i.imgur.com/2ty77wr.png https://i.imgur.com/js6wnaw.png Hi found an issue for some reason after I have cooked so many sausages apparently I don't have any more sausages to cook even though I have sausage in my inventory i have tried restarting the resource but for some reason, it still fails. Also, I found an error in your code you put sausage_processing instead of sausage_progressbar. Hope you can find a fix for this. PS the cooked sausages in my inventory are 6, not 0 my screenshot is broken. Thank you for such an amazing resource keep up the amazing work.

What version of this resource are you using? and what exactly are you doing when you are getting this error https://imgur.com/2ty77wr

sending a cropped screenshot doesn't really give me any inside into what you are trying to do.

**Comment by skellykat** [comment]
Hi sorry for the late reply, I am using the latest version of the resource. The way I was receiving the error was when I was trying to cook the sausages at the house you showed in the video I was doing everything you did in the video and then for some reason it just randomly stopped working and when I tried restarting the resource to reset it the error still came back. After i restarted the resource and my server this morning the error seemed to have gone away. The error seemed to only occur when i was giving myself the raw_sausage item and not getting it from the pigs. Sorry for any confusion caused the error is now fixed. If you give yourself raw_sausage the system breaks until you get rid of said sausages. PS. i did find the image of the broken text in the progress bar. https://i.imgur.com/6aKyA24.png

**Comment by rafaelval** [comment]
i got it! just change on /client/main.lua line 1460 

this: 
RegisterNetEvent('qb-simplefarming:sausageprocessing', function()
  QBCore.Functions.TriggerCallback('qb-simplefarming:rawpork', function(rawbeef)

for this:
RegisterNetEvent('qb-simplefarming:sausageprocessing', function()
  QBCore.Functions.TriggerCallback('qb-simplefarming:rawsausage', function(rawbeef)

**Comment by rafaelval** [comment]
by the way, very good job, it's awesome

**Comment by rafaelval** [comment]
![image](https://user-images.githubusercontent.com/84647580/194810063-844920bd-0353-4080-981b-7c5cf6cea35a.png)
this is the pice of code, with the change in the sausage_progressbar
