### ISSUE TITLE
Types of meat

### ISSUE THREAD

**Issue by Motofam** [trclassic92/qb-simplefarming#5]
Good morning, i have noticed you have added all meats besides chickens? was that intended to be on here or left out on purpose? chickens are part of the whole farming process and cant seem to notice them in this script. otherwise. great work!

**Comment by trclassic92** [comment]
Yes, it was intended to be left out as I couldn't really find a good way to implement it correctly. But it will be added in the future.

**Comment by Motofam** [comment]
i managed to somewhat implement it the same as pigs. where you have a pen of them spawn and walk up slaughter the chickens and take slaughtered chicken meat and process into chickenbreasts. possible to implement that way maybe?

**Comment by trclassic92** [comment]
> i managed to somewhat implement it the same as pigs. where you have a pen of them spawn and walk up slaughter the chickens and take slaughtered chicken meat and process into chickenbreasts. possible to implement that way maybe?

Yes it is possible.
