### ISSUE TITLE
Not a job

### ISSUE THREAD

**Issue by milotiro95** [trclassic92/qb-simplefarming#7]
Hi. Thank you for the awesome script. 
Do you think it's possible to update this script to be a job also the blip too ? Like farmer
Because blips is important for worker but not for everyone.

**Comment by trclassic92** [comment]
> Hi. Thank you for the awesome script. Do you think it's possible to update this script to be a job also the blip too? Like farmer Because blips is important for the worker but not for everyone.

The script will always get updated... its not one of my projects that I put up and just leave it out to gather dust if that makes sense..

But as far as a job being added to this... that was never the intention for this script.. You are more than welcome to adapt to the script and add a job function you're self as stated in the license on the script.

**Comment by milotiro95** [comment]
I understand no problem it is just a simple ask if you cannot do it I totally understand. I try to adapt for blips for idk why for now I havn't got it work well.

**Comment by vBooya** [comment]
he can do it, but as he said that wasnt the intention of the script therefore he isnt planning on doing it lmao
