### ISSUE TITLE
Is it possible to create different sellers?

### ISSUE THREAD

**Issue by PlodyIce** [trclassic92/qb-simplefarming#9]
Hey Mate, I love your script.

I wanted to ask if it would be possible to create multiple sellers who buy different products. 

Like:
- Fruit seller
- meat merchant
- Dairyman

**Comment by trclassic92** [comment]
Yes it is possible....

**Comment by PlodyIce** [comment]
Oh really? I didn't find a function for that in the script? Maybe Im blind xD

**Comment by trclassic92** [comment]
> Oh really? I didn't find a function for that in the script? Maybe Im blind xD

No you will have to add the feature for it... Its pretty easy to do. But I basically am making all the sellers in one location. But maybe in the feature I will add a feature that supports this option

**Comment by PlodyIce** [comment]
Oh okay, Im new to lua... I will try doing it by myself. Thanks anyway :)

**Comment by trclassic92** [comment]
The file location you will need to edit for these features you are asking for is going to be in the server lua 😄
